export default {
  id: 0,
  claimant: "",
  userId: 0,
  cityId: 0,
  agencyId: 0,
  place: "",
  dateInit: "",
  dateEnd: "",
  detail: "",
  title: "",
  status: 0,
  finding: "",
  conclusions: "",
  userIdResponsible: 0,
  isInternal: 0,
  support: [],
  caseMedias: [],
  participants: [],
  comments: [],
};
